-- ANALYSIS QUESTIONS
USE project;

SELECT * FROM ZomatoData1;

-- ROLLING/MOVING COUNT OF RESTAURANTS IN INDIAN CITIES
SELECT COUNTRY_NAME, City, Locality, COUNT(Locality) AS TOTAL_REST,
    SUM(COUNT(Locality)) OVER(PARTITION BY City ORDER BY Locality DESC) AS RollingCount
FROM ZomatoData1
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY COUNTRY_NAME, City, Locality;

-- SEARCHING FOR PERCENTAGE OF RESTAURANTS IN ALL THE COUNTRIES
CREATE OR REPLACE VIEW TOTAL_COUNT AS
SELECT DISTINCT(COUNTRY_NAME), COUNT(CAST(RestaurantID AS DECIMAL)) AS TOTAL_REST
FROM ZomatoData1;

SELECT * FROM TOTAL_COUNT;

-- FINAL QUERY AFTER CREATING VIEW
WITH CT1 AS (
    SELECT COUNTRY_NAME, COUNT(CAST(RestaurantID AS DECIMAL)) AS REST_COUNT
    FROM ZomatoData1
    GROUP BY COUNTRY_NAME
)
SELECT A.COUNTRY_NAME, A.REST_COUNT,
    ROUND(CAST(A.REST_COUNT AS DECIMAL) / CAST(B.TOTAL_REST AS DECIMAL) * 100, 2) AS Percentage
FROM CT1 A
JOIN TOTAL_COUNT B ON A.COUNTRY_NAME = B.COUNTRY_NAME
ORDER BY 3 DESC;

-- WHICH COUNTRIES AND HOW MANY RESTAURANTS WITH PERCENTAGE PROVIDES ONLINE DELIVERY OPTION
CREATE OR REPLACE VIEW COUNTRY_REST AS
SELECT COUNTRY_NAME, COUNT(CAST(RestaurantID AS DECIMAL)) AS REST_COUNT
FROM ZomatoData1
GROUP BY COUNTRY_NAME;

SELECT * FROM COUNTRY_REST ORDER BY 2 DESC;

SELECT A.COUNTRY_NAME, COUNT(A.RestaurantID) AS TOTAL_REST,
    ROUND(COUNT(CAST(A.RestaurantID AS DECIMAL)) / CAST(B.REST_COUNT AS DECIMAL) * 100, 2) AS Percentage
FROM ZomatoData1 A
JOIN COUNTRY_REST B ON A.COUNTRY_NAME = B.COUNTRY_NAME
WHERE A.Has_Online_delivery = 'YES'
GROUP BY A.COUNTRY_NAME, B.REST_COUNT
ORDER BY 2 DESC;

-- FINDING FROM WHICH CITY AND LOCALITY IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS (
    SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM ZomatoData1
    WHERE COUNTRY_NAME = 'INDIA'
    GROUP BY CITY, LOCALITY
)
SELECT Locality, REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1);

-- TYPES OF FOODS ARE AVAILABLE IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS (
    SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM ZomatoData1
    WHERE COUNTRY_NAME = 'INDIA'
    GROUP BY CITY, LOCALITY
),
CT2 AS (
    SELECT Locality, REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
)
SELECT A.Locality, B.Cuisines
FROM CT2 A
JOIN ZomatoData1 B ON A.Locality = B.Locality;

-- MOST POPULAR FOOD IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
CREATE VIEW VF AS
SELECT COUNTRY_NAME, City, Locality, SPLIT_STR(Cuisines, '|', N) AS Cuisines
FROM ZomatoData1
CROSS JOIN (SELECT 1 AS N UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) Numbers
WHERE N <= LENGTH(Cuisines) - LENGTH(REPLACE(Cuisines, '|', '')) + 1;

WITH CT1 AS (
    SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM ZomatoData1
    WHERE COUNTRY_NAME = 'INDIA'
    GROUP BY CITY, LOCALITY
),
CT2 AS (
    SELECT Locality, REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
)
SELECT A.Cuisines, COUNT(A.Cuisines) AS CuisinesCount
FROM VF A
JOIN CT2 B ON A.Locality = B.Locality
GROUP BY B.Locality, A.Cuisines
ORDER BY 2 DESC;

-- WHICH LOCALITIES IN INDIA HAS THE LOWEST RESTAURANTS LISTED IN ZOMATO
WITH CT1 AS (
    SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM ZomatoData1
    WHERE COUNTRY_NAME = 'INDIA'
    GROUP BY City, Locality
)
SELECT * FROM CT1 WHERE REST_COUNT = (SELECT MIN(REST_COUNT) FROM CT1) ORDER BY CITY;

-- HOW MANY RESTAURANTS OFFER TABLE BOOKING OPTION IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS (
    SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM ZomatoData1
    WHERE COUNTRY_NAME = 'INDIA'
    GROUP BY CITY, LOCALITY
),
CT2 AS (
    SELECT Locality, REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)
),
CT3 AS (
    SELECT Locality, Has_Table_booking AS TABLE_BOOKING
    FROM ZomatoData1
)
SELECT A.Locality, COUNT(A.TABLE_BOOKING) AS TABLE_BOOKING_OPTION
FROM CT3 A
JOIN CT2 B ON A.Locality = B.Locality
WHERE A.TABLE_BOOKING = 'YES'
GROUP BY A.Locality;

-- HOW RATING AFFECTS IN MAX LISTED RESTAURANTS WITH AND WITHOUT TABLE BOOKING OPTION (Connaught Place)
SELECT 'WITH_TABLE' AS TABLE_BOOKING_OPT, COUNT(Has_Table_booking) AS TOTAL_REST,
    ROUND(AVG(Rating), 2) AS AVG_RATING
FROM ZomatoData1
WHERE Has_Table_booking = 'YES'
AND Locality = 'Connaught Place'
UNION
SELECT 'WITHOUT_TABLE' AS TABLE_BOOKING_OPT, COUNT(Has_Table_booking) AS TOTAL_REST,
    ROUND(AVG(Rating), 2) AS AVG_RATING
FROM ZomatoData1
WHERE Has_Table_booking = 'NO'
AND Locality = 'Connaught Place';

-- AVG RATING OF RESTS LOCATION WISE
SELECT COUNTRY_NAME, City, Locality,
    COUNT(RestaurantID) AS TOTAL_REST,
    ROUND(AVG(CAST(Rating AS DECIMAL)), 2) AS AVG_RATING
FROM ZomatoData1
GROUP BY COUNTRY_NAME, City, Locality
ORDER BY 4 DESC;

-- FINDING THE BEST RESTAURANTS WITH MODERATE COST FOR TWO IN INDIA HAVING INDIAN CUISINES
SELECT *
FROM ZomatoData1
WHERE COUNTRY_NAME = 'INDIA'
AND Has_Table_booking = 'YES'
AND Has_Online_delivery = 'YES'
AND Price_range <= 3
AND Votes > 1000
AND Average_Cost_for_two < 1000
AND Rating > 4
AND Cuisines LIKE '%INDIA%';

-- FIND ALL THE RESTAURANTS THOSE WHO ARE OFFERING TABLE BOOKING OPTIONS WITH PRICE RANGE AND HAS HIGH RATING
SELECT Price_range, COUNT(Has_Table_booking) AS NO_OF_REST
FROM ZomatoData1
WHERE Rating >= 4.5
AND Has_Table_booking = 'YES'
GROUP BY Price_range;
